### ISSUE TITLE
Boat Level

### ISSUE THREAD

**Issue by Sheadyatwork** [EssexGroupProject12/GameJam#1]
Tasks:
- New Scene
- Boat functionality of sliding instead of multi-directional
- Fishing hook functionality / Collecting item functionality
- Update upgrade / downgrade functionality towards a boat
- Sonar position change + range

**Comment by Sheadyatwork** [comment]
Tasks:

- New Scene : DONE
- Boat functionality of sliding instead of multi-directional : TODO
- Fishing hook functionality / Collecting item functionality : TODO
- Update upgrade / downgrade functionality towards a boat : TODO
- Sonar position change + range : TODO

**Comment by T-0pel** [comment]
Tasks:

New Scene : DONE
Boat functionality of sliding instead of multi-directional : DONE
Fishing hook functionality / Collecting item functionality : DONE
Update upgrade / downgrade functionality towards a boat : TODO
Sonar position change + range : DONE
